### ISSUE TITLE
PHP Warning:  Declaration of rcube_sieve_vacation

### ISSUE THREAD

**Issue by CRtEurope** [roundcube/roundcubemail#5280]
I am getting this error permanently:

`PHP Warning:  Declaration of rcube_sieve_vacation::load_script() should be compatible with rcube_sieve_engine::load_script($script_name = NULL) in /plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php on line 24`

`Warning: Call to deprecated function Q(); See bc.inc for replacement`

PHP 7.0, branch: master
pear NET_SIEVE 1.3.4

**Comment by alecpl** [comment]
This is fixed in 1.2.0 and this is the only version working with PHP7.

**Comment by alecpl** [comment]
Oh, you said it's master. Not true.

**Comment by CRtEurope** [comment]
Yup, master

**Comment by alecpl** [comment]
https://github.com/roundcube/roundcubemail/blob/master/plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php#L56
https://github.com/roundcube/roundcubemail/blob/master/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php#L231

**Comment by CRtEurope** [comment]
I already have it. Just made a clean install of the plugin by redownloading it. Server reboot. Cleared cache of each browser, still the same errors in the log file.

**Comment by CRtEurope** [comment]
Have done a real clean installation now.
PHP 7.07
Branch: master-branch
pear Net_Sieve 1.3.4

Now only this error shows up in the log files:
`PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Net_Sieve has a deprecated constructor in /usr/share/php/Net/Sieve.php on line 93`

Mybe this error helps along?

**Comment by alecpl** [comment]
Use composer to install dependencies or get them from the official release. Net_Sieve from PEAR does not support PHP7. We forked it to https://github.com/roundcube/Net_Sieve.

**Comment by CRtEurope** [comment]
Did it. Working great now.
This ticket can be finally closed now.

Thanks a lot Alec!
