### ISSUE TITLE
Issue after upgrade to 1.4-git

### ISSUE THREAD

**Issue by reficul** [roundcube/roundcubemail#6534]
<img width="1073" alt="schermata 2018-11-27 alle 12 10 19" src="https://user-images.githubusercontent.com/1073883/49078151-8ac6a080-f23d-11e8-8fc3-d19b1e777aa4.png">

It seems that all mails info are stored in the first column, all others blank.
Any help?

**Comment by reficul** [comment]
Issue present only with "Widescreen" display option enabled.

**Comment by alecpl** [comment]
I'm unable to reproduce on git-master. For a user with such preferences after login I see correct widescreen mode. What do you have in `layout`, `skin` and `dont_override` options in config?

**Comment by reficul** [comment]
$config['dont_override'] = array();
$config['layout'] = 'widescreen';
$config['skin'] = 'larry';

**Comment by alecpl** [comment]
Could you verify with 1.4-rc1? I still wasn't able to reproduce.

**Comment by ttimmy** [comment]
Hello. Got here from a Mailinabox setup (mailinabox.email) that has roundcube installed. I'm having this issue and can reproduce 100% of the time (Firefox, Mac laptop).
Output of `apt list`:

`
roundcube/trusty 0.9.5-4 all
roundcube-core/trusty 0.9.5-4 all
roundcube-mysql/trusty 0.9.5-4 all
roundcube-pgsql/trusty 0.9.5-4 all
roundcube-plugins/trusty 0.9.5-4 all
roundcube-plugins-extra/trusty 0.9.2-20130819 all
roundcube-sqlite3/trusty 0.9.5-4 all
`

How can I help?

**Comment by alecpl** [comment]
@ttimmy No, it's too old version.

**Comment by alecpl** [comment]
Assuming fixed in 1.4-rc1.

**Comment by ttimmy** [comment]
Strange, when I do apt list the version is listed as 0.9.5-4, but when I click About in Roundcube it says version 1.3.8, and I can reproduce it. I'll wait until Mailinabox will upgrade to 1.4-rc1 or above and reopen this if I can reproduce.

**Comment by ttimmy** [comment]
![Screen Shot 2019-05-13 at 9 09 30 PM](https://user-images.githubusercontent.com/10391916/57663823-9a575d00-75c3-11e9-91d9-61c92c35a0df.png)

**Comment by jvolkenant** [comment]
> 
> 
> Assuming fixed in 1.4-rc1.



![image](https://user-images.githubusercontent.com/10521453/63107760-654c0500-bf3a-11e9-8f54-a5f3c3947d31.png)


Problem still exists in 1.4-rc1. Seems to happen when I leave page up for a few days.

**Comment by ttimmy** [comment]
> > Assuming fixed in 1.4-rc1.
> 
> ![image](https://user-images.githubusercontent.com/10521453/63107760-654c0500-bf3a-11e9-8f54-a5f3c3947d31.png)
> 
> Problem still exists in 1.4-rc1. Seems to happen when I leave page up for a few days.
> 
> Refreshing the URL (which is already in the address bar) https://example.com/mail/?_task=mail&_mbox=INBOX&_action=refresh does not work, I have to remove "?_task=mail&_mbox=INBOX&_action=refresh" from the url to get the page to cooperate

@alecpl I think this issue needs to be reopened
