### ISSUE TITLE
Elastic: delete button too far from list of mails

### ISSUE THREAD

**Issue by bes-internal** [roundcube/roundcubemail#7141]
I think many people are familiar with the situation when you can delete a letter-notification without even reading it. Now it is difficult to make it using mouse: you need to select the letter, find toolbar on the right side, delete it and then return to the list of letters.

![0](https://user-images.githubusercontent.com/2046529/71722777-31b33e00-2e3b-11ea-8e28-1277c0d33be8.png)

I suggest the following improvements:
1. Add delete button to the top of the list of letters to delete an opened letter 
2. Add delete on hover to delete without reading

![1](https://user-images.githubusercontent.com/2046529/71722850-82c33200-2e3b-11ea-8cc6-e23970e77708.png)

**Comment by alecpl** [comment]
1. You can select message(s) with click and CTRL key to select message(s) without opening.
2. You can install contextmenu plugin.

Anyway, maybe we should consider other options, but I don't really like proposed options.

**Comment by manfredu** [comment]
My opinion: Two Delete buttons with the same functionality are confusing. You can also use DEL key from the keyboard for fast action.

Also there are more buttons on the right column above the open mail which work on a list of selected mails (middle column)...

I do agree that the placement of the buttons is a bit confusing in the beginnung, but I got used to it.

The only other option I can imagine of would be to have all buttons together in one place. But I would leave it as it is.

**Comment by bes-internal** [comment]
consider the logic of a similar interface
![2020-01-10_14-23](https://user-images.githubusercontent.com/2046529/72149841-17d2a780-33b5-11ea-8218-3cc6b927e692.png)

**Comment by manfredu** [comment]
So the buttons on the right side affects only the currently displayed mail? 

This means all buttons which can affect several selected mails would need to be copied to the middle column (i.e. forward, delete mark, more... ).

**Comment by manfredu** [comment]
Or have a row of buttons, which can affect one or more mails, across both columns and move buttons, which can be only used for the currently open mail, into the window of the displayed mail... Similiar to above screenshot.

**Comment by bes-internal** [comment]
Yes. On above screenshot this is first button for forward. 
The meaning of any UI is to reduce the time and number of gestures of the most popular functions.
Let's do delete at least on hover of message in Elastic. Mark or delete. This is most popular quick functions.

P.S. I speak not only from myself. But from a significant number of our customers who use the new interface. I have already received more than 20 applications about the inconvenience of deleting in the new interface.

**Comment by alecpl** [comment]
I think you're too late for fundamental layout changes in Elastic. We will however, consider doing something with the Delete action as indeed it is most common action.

**Comment by bes-internal** [comment]
Unfortunately I do not use roundcube, but my clients do it. Thanks

**Comment by idl0r** [comment]
I also have that issue. +1 for that proposals above. Like it was on the "Larry" style. Also a JS right-click menu might make sense to also offer the same options.

**Comment by manfredu** [comment]
> [...] Also a JS right-click menu might make sense to also offer the same options.

I use the contextmenu plugin, which imho does what you are looking for.

**Comment by idl0r** [comment]
> > [...] Also a JS right-click menu might make sense to also offer the same options.
> 
> I use the contextmenu plugin, which imho does what you are looking for.

Yup, it does.

**Comment by Dave-09** [comment]
+1. Here too it is missed by customers as described above. Can it not be added as Outlook has?

**Comment by dinsdalepiranha** [comment]
+1 for sure.  The ability to delete a message without selecting that message (or ending up with any other message selected) would be a massive improvement.

**Comment by CombeeMike** [comment]
+1 Same reasons as already mentioned (long mouse distances, context menu is an improvement but IMHO still too many needless clicks).

Since I'm currently fiddling around with building my own skin which extends from elastic:
Is it somehow possible to add that functionality using my own skin? Actually, I'd rather replace the "flag" hover action with "remove" if possible as I don't use flags at all...

**Comment by CombeeMike** [comment]
Ps.: This is how I'd imagine the styling in combination with the dark elastic skin (inspired by MS OWA):
![image](https://user-images.githubusercontent.com/30658772/218493494-32f302e3-ee8e-467e-a58c-1011369fca35.png)

Implementing those styles in my custom skin was rather issue but the button (obviously) still flags the mail instead of deleting it and I don't know if there's a way to overwrite or customize that behavior somehow 🤷‍♂️

**Comment by alecpl** [comment]
Implemented as a hover menu like this:

![list-hover-menu](https://github.com/roundcube/roundcubemail/assets/546788/0b547586-11be-42ce-805b-acb054d136de)

I'm not fully happy about it though. If people don't like it we can consider removing it or making optional (or a plugin).

**Comment by gianlucagiacometti** [comment]
I just tried this new solution and I hope you don't mind if I point out a couple of things:

1. Probably a 50% transparent background it would be less impacting

2. The general Delete button does not work any more; this is the error in the console:
```
Uncaught TypeError: data is null
    selection_post_data https://mywebsite/program/js/app.js?s=1687791710:3415
    permanently_remove_messages https://mywebsite/program/js/app.js?s=1687791710:3339
    delete_messages https://mywebsite/program/js/app.js?s=1687791710:3317
    command_handler https://mywebsite/program/js/app.js?s=1687791710:1015
    command https://mywebsite/program/js/app.js?s=1687791710:773
    onclick https://mywebsite/?_task=mail&_mbox=Trash#:1
```

**Comment by alecpl** [comment]
1. Opacity does not make sense.
2. Fixed.

**Comment by oleg-indeez** [comment]
Hello. After last git up and this feature I have the following regression:
1. at INBOX folder `Shift+Del` fires the dialog, asking me to confirm but the ok-button can not be pressed neither by keyboard no by the mouse. `Del` works as expected. Operations are quite the same with one or several emails selection.
2. at Thrash folder: `Del` (and `Shift+Del`) key has no visual effect at all; if I press trashbin-icon at the mouse-over menu it report that the file is deleted but mail list is not updated and this just-purged mail is still shown there. Obviously, when I try to select this mail again roundcube reports that there's no such mail at the server. This can be fixed by full page reload only (e.g. `Ctrl+Shift+R`)

**Comment by oleg-indeez** [comment]
update: case 1 is true for all the folders but Thrash

**Comment by alecpl** [comment]
Fixed.

**Comment by oleg-indeez** [comment]
sorry to interrupt you once more but there's another regression still in: if I delete email (at INBOX folder) by holding shift and clicking trashbin-icon, RoundCube asks me to confirm and purges that e-mail, but after that it's still shown in the leftmost mail list. If I select it there - server error 'there's no such message'; changing folders or full page reload helps.

**Comment by alecpl** [comment]
Fixed. Thanks for testing and patience.

**Comment by oleg-indeez** [comment]
Thank you for the great webmail system!
Ok, now it works but I wand to draw your attention on these two points: first, when I click the trashbin-icon while holding `shift`, and if it asks for my confirmation - if I confirm by pressing Enter while the mouse pointer is at leftmost mail list - RoundCube purges the mail, update leftside mail list and draws 1px black solid border across it (possibly set focus there). It seems to me that the last action is excessive a bit =)
and the second thought: it's not obvious that when one press, for example, "mark flagged" icon while there's a group of selected e-mails, the flag mark applies only to one e-mail and not the whole group. I'm not meaning that this is a error but such a behaviour is imho not obvious and I'd expect that the action be applied to all the selected e-mails. Left it here just for your consideration.
Thank you once more for the great webmail interface, your time and patience!

**Comment by TLRS-Sandwich** [comment]
> Implemented as a hover menu like this:
> 
> ![list-hover-menu](https://github.com/roundcube/roundcubemail/assets/546788/0b547586-11be-42ce-805b-acb054d136de)
> 

I Ctrl-clicked to do multiple messages and the hover button came up. Assuming it was like a right-click in Outlook, I thought it would delete all the ones I'd selected but it only did the one. I am okay with explaining this away for our customers, but it was definitely confusing for me when I first encountered it as I work more in Classic than I do Elastic for testing and troubleshooting.
