### ISSUE TITLE
enigma plugin: Default keyserver is no longer active

### ISSUE THREAD

**Issue by phonon112358** [roundcube/roundcubemail#7373]
Unfortunately, the default key server ( `keys.fedoraproject.org` )of the enigma plugin is no longer available. For more information see https://fedoraproject.org/wiki/Infrastructure/graveyard
I would propose to define `keys.openpgp.org` as default one in future releases of the plugin.

**Comment by alecpl** [comment]
Is `keys.openpgp.org` working for you? I found recently in #7367 that most key servers do not support CORS and do not work in Roundcube. Only `keys.gnupg.net` works. On the other hand, that CORS thing is strange because I'm sure it worked in the past (when we implemented the searching).

**Comment by chaos-prevails** [comment]
Hi,

I encounter the same problem today:
http://keys.openpgp.org
--> Blocked loading mixed active content “http://keys.openpgp.org/pks/lookup?op=index&options=mr&fingerprint=on&search=XXX” publickey.min.js:37:53

(and I think it would not be good to download public keys via http)

https://keys.openpgp.org
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://keys.openpgp.org/pks/lookup?op=index&options=mr&fingerprint=on&search=XXX. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

same with others which work in the browser, e.g. https://keyserver.ubuntu.com/

as long as server-side search #7367 is not implemented. Is there any gpg keyserver which allows all CORs?

**Comment by phonon112358** [comment]
no, keys.openpgp.org doesn't work. The CORS error was, btw., also the cause for https://github.com/roundcube/roundcubemail/issues/7334.
However, even keys.gnupg.net doesn't work at my instance due to a "certificate authority is invalid" error...

**Comment by phonon112358** [comment]
Now, `keys.openpgp.org` does work well! see https://github.com/roundcube/roundcubemail/issues/7367

**Comment by chaos-prevails** [comment]
Hi,
thanks, it still doesn't work for me, also not with an email address with which a valid key can be found.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://keys.openpgp.org/search?q=valid-user%40valid-domain.at. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

I adapted the server + search query for 1.3.11

**Comment by alecpl** [comment]
@chaos-prevails you should be using /pks/lookup url.

**Comment by alecpl** [comment]
Fixed.
