### ISSUE TITLE
Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200

### ISSUE THREAD

**Issue by diego1estrada** [roundcube/roundcubemail#7408]
We use and like roundcube in our company

whith out reason (no update, no change, nothing, stop working.

this is the log file

the firts 2 lines, it was working fine; On May 30 stop working 

[28-May-2020 16:08:58 -0500]: <2aae7139> IMAP Error: Login failed for juan.garcia@hotmail.com against mail.ingentar.com from 191.89.65.152. AUTHENTICATE LOGIN: A0001 NO [AUTHENTICATIONFAILED] Authentication failed. in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[29-May-2020 13:36:37 -0500]: <5f577913> IMAP Error: Login failed for auxiliaringenieria@frigriteamerica.com against mail.ingentar.com from 181.137.73.210. AUTHENTICATE LOGIN: A0001 NO [AUTHENTICATIONFAILED] Authentication failed. in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 05:48:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 05:49:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 05:50:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 05:51:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 05:52:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 05:53:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 05:54:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 05:55:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 05:56:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 05:57:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:03:01 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:03:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:04:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:05:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:06:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:07:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:08:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:09:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:10:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:11:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:17:01 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:17:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:18:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:19:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:20:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:21:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:22:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:23:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:24:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:25:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:31:01 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:31:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:32:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:33:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:34:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:35:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:36:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:37:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:38:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 06:39:58 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)
[30-May-2020 08:57:11 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 08:57:16 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 08:58:34 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 09:03:45 -0500]: <debf5bfe> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 09:03:59 -0500]: <4c3e7ae8> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 191.89.75.208. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 09:04:56 -0500]: <661a5563> IMAP Error: Login failed for sistemas@efitrans.com against mail.ingentar.com from 191.89.75.208. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 09:10:13 -0500]: <f6dfd5f2> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 191.89.75.208. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 09:14:52 -0500]: <f6dfd5f2> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 191.89.75.208. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 09:18:05 -0500]: <f6dfd5f2> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 191.89.75.208. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 09:27:16 -0500]: <f6dfd5f2> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 191.89.75.208. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 09:38:27 -0500]: <f6dfd5f2> IMAP Error: Login failed for diego.estrada@ingentar.com against localhost from 191.89.75.208. Could not connect to ssl://localhost:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 09:46:08 -0500]: <f6dfd5f2> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 191.89.75.208. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 09:49:16 -0500]: <f6dfd5f2> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 191.89.75.208. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:05:59 -0500]: <93b6f0f9> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 191.89.75.208. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:08:40 -0500]: <345ea3ef> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:15:30 -0500]: <345ea3ef> IMAP Error: Login failed for diego.estrada@ingentar.com against localhost from 192.168.2.45. Could not connect to ssl://localhost:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:17:20 -0500]: <345ea3ef> IMAP Error: Login failed for diego.estrada@ingentar.com against 127.0.0.1 from 192.168.2.45. Could not connect to ssl://127.0.0.1:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:18:14 -0500]: <345ea3ef> IMAP Error: Login failed for diego.estrada@ingentar.com against 192.168.88.8 from 192.168.2.45. Could not connect to ssl://192.168.88.8:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:31:29 -0500]: <345ea3ef> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:36:00 -0500]: <ffd7eb76> IMAP Error: Login failed for administracion@efitrans.com against mail.ingentar.com from 181.143.86.67. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:36:12 -0500]: <ffd7eb76> IMAP Error: Login failed for administracion@efitrans.com against mail.ingentar.com from 181.143.86.67. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:36:30 -0500]: <ffd7eb76> IMAP Error: Login failed for comercial2@easytransvip.com against mail.ingentar.com from 181.143.86.67. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:36:41 -0500]: <ffd7eb76> IMAP Error: Login failed for comercial2@efitrans.com against mail.ingentar.com from 181.143.86.67. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:42:21 -0500]: <345ea3ef> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:43:04 -0500]: <8a3dc846> IMAP Error: Login failed for info@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:43:10 -0500]: <8a3dc846> IMAP Error: Login failed for info@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:43:32 -0500]: <8a3dc846> IMAP Error: Login failed for comercial@efitrans.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:43:57 -0500]: <8a3dc846> IMAP Error: Login failed for gerenciagrupo@efitrans.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
[30-May-2020 11:47:12 -0500]: <345ea3ef> IMAP Error: Login failed for diego.estrada@ingentar.com against mail.ingentar.com from 192.168.2.45. Could not connect to ssl://mail.ingentar.com:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)

**Comment by alecpl** [comment]
Maybe certificate problem. There's not much we can help here.

**Comment by thomascube** [comment]
This sort of errors have been reported in conjunction with Letsencrypt certificates being used on the IMAP server. PHP seems to reject them and thus Roundcube cannot open a connection. Unfortunately that's a problem if PHP and/or your server's operating system and we can't fix in on application level.

**Comment by selbep** [comment]
Uffff, what a headache!
Just `apt install ca-certificates` and it works!

**Comment by ErikasRaginis** [comment]
I'm having the same issue, has anyone managed to resolve this? ca-certificates are already installed for me.

**Comment by ThomasCr** [comment]
I have the same problem. To test if it related to certificate validation, you can test to disable verification:
`$config['imap_conn_options'] = array('ssl' => array('verify_peer' => false));`

If thats is the problem, check if 1. ca-certificates are installed and 2. if your php.ini contains:
```
[openssl]
openssl.cafile=/etc/ssl/certs/ca-certificates.crt
openssl.capath=/etc/ssl/certs
```
Check if this is the right locations (they are from ubuntu)

Also your PHP process needs access rights to it (check open_basedir or chroot options)

**Comment by Tofandel** [comment]
I tried disabling `verify_peer` but the issue persists

```
[12-Apr-2023 12:17:17 UTC] PHP Warning:  stream_socket_client(): SSL: Success in /usr/share/psa-roundcube/program/lib/Roundcube/rcube_imap_generic.php on line 1060
[12-Apr-2023 12:17:17 UTC] PHP Warning:  stream_socket_client(): Failed to enable crypto in /usr/share/psa-roundcube/program/lib/Roundcube/rcube_imap_generic.php on line 1060
[12-Apr-2023 12:17:17 UTC] PHP Warning:  stream_socket_client(): Unable to connect to ssl://localhost:993 (Unknown error) in /usr/share/psa-roundcube/program/lib/Roundcube/rcube_imap_generic.php on line 1060
[12-Apr-2023 12:17:17 +0000]: <37b39dd5> IMAP Error: Login failed for ***** against localhost from ****. Could not connect to ssl://localhost:993: Unknown reason in /usr/share/psa-roundcube/program/lib/Roundcube/rcube_imap.php on line 211 (POST /?_task=mail&_action=refresh)
```

Seeing `SSL: success` I don't know what is the issue

**Comment by riyanflush** [comment]
> I tried disabling `verify_peer` but the issue persists
> 
> ```
> [12-Apr-2023 12:17:17 UTC] PHP Warning:  stream_socket_client(): SSL: Success in /usr/share/psa-roundcube/program/lib/Roundcube/rcube_imap_generic.php on line 1060
> [12-Apr-2023 12:17:17 UTC] PHP Warning:  stream_socket_client(): Failed to enable crypto in /usr/share/psa-roundcube/program/lib/Roundcube/rcube_imap_generic.php on line 1060
> [12-Apr-2023 12:17:17 UTC] PHP Warning:  stream_socket_client(): Unable to connect to ssl://localhost:993 (Unknown error) in /usr/share/psa-roundcube/program/lib/Roundcube/rcube_imap_generic.php on line 1060
> [12-Apr-2023 12:17:17 +0000]: <37b39dd5> IMAP Error: Login failed for ***** against localhost from ****. Could not connect to ssl://localhost:993: Unknown reason in /usr/share/psa-roundcube/program/lib/Roundcube/rcube_imap.php on line 211 (POST /?_task=mail&_action=refresh)
> ```
> 
> Seeing `SSL: success` I don't know what is the issue

has you problem has been solved? i have same problem.

**Comment by Britaliope** [comment]
@Tofandel @riyanflush I had this problem, and just successfully passed the imap check by also disabling verify_peer_name :
```php
$config['imap_conn_options'] = [
  'ssl'         => [
     'verify_peer'  => false,
      'verify_peer_name' => false,
   ],
];
```

I am still investigating this issue and not quite understanding what is happening, but this might be useful for you anyway

**Comment by C0rn3j** [comment]
I was migrating from `mail.example.pw` to `mail.example.rs` but needed both domains and only had `mail.example.pw` cert on dovecot and postfix.  
Unsure why EXACTLY this is happening, but one can check the name on the IMAP server like so:

```bash
[0] % openssl s_client -showcerts -connect mail.example.rs:993 -servername mail.example.rs </dev/null 2>/dev/null| grep '^subject'
subject=CN=mail.example.pw
```

Unsure why Roundcube is expecting a specific cert, as accessing it through both pw and rs fails.  

Here's where it was used on my setup:
```ini
files/postfix/main.cf:smtpd_tls_cert_file = /etc/letsencrypt/live/mail.example.pw/fullchain.pem
files/postfix/main.cf:smtpd_tls_key_file = /etc/letsencrypt/live/mail.example.pw/privkey.pem
files/dovecot.conf:ssl_cert = </etc/letsencrypt/live/mail.example.pw/fullchain.pem
files/dovecot.conf:ssl_key = </etc/letsencrypt/live/mail.example.pw/privkey.pem
```

The errors still look like this:

```php
[17-Aug-2024 17:20:38 +0000]: <2kss5d1m> IMAP Error: Login failed for martin@example.rs against [2001:bc8:1640:1c45:216:3eff:fe2f:1234] from 109.80.37.217. Could not connect to ssl://[2001:bc8:1640:1c45:216:3eff:fe2f:1234]:993: Unknown reason in /usr/share/webapps/roundcubemail/program/lib/Roundcube/rcube_imap.php on line 211 (POST /webmail/?_task=login&_action=login)
[17-Aug-2024 17:22:06 +0000]: <2kss5d1m> IMAP Error: Login failed for martin@example.pw against mail.example.rs from 109.80.37.217. Could not connect to ssl://mail.example.rs:993: Unknown reason in /usr/share/webapps/roundcubemail/program/lib/Roundcube/rcube_imap.php on line 211 (POST /webmail/?_task=login&_action=login)
```

One time at the end of my testing with all the debug params on, a proper error managed to bubble through in the form of a PHP Warning. The error Roundcube throws is still `Unknown reason`, and the web UI says absolutely nothing useful.

```php
[17-Aug-2024 17:37:10 UTC] PHP Warning:  stream_socket_client(): Peer certificate CN=`mail.example.pw' did not match expected CN=`mail.example.rs' in /usr/share/webapps/roundcubemail/program/lib/Roundcube/rcube_imap_generic.php on line 1059
[17-Aug-2024 17:37:10 UTC] PHP Warning:  stream_socket_client(): Failed to enable crypto in /usr/share/webapps/roundcubemail/program/lib/Roundcube/rcube_imap_generic.php on line 1059
[17-Aug-2024 17:37:10 UTC] PHP Warning:  stream_socket_client(): Unable to connect to ssl://mail.example.rs:993 (Unknown error) in /usr/share/webapps/roundcubemail/program/lib/Roundcube/rcube_imap_generic.php on line 1059
[17-Aug-2024 17:37:10 +0000]: <2kss5d1m> IMAP Error: Login failed for martin@example.pw against mail.example.rs from 109.80.37.217. Could not connect to ssl://mail.example.rs:993: Unknown reason in /usr/share/webapps/roundcubemail/program/lib/Roundcube/rcube_imap.php on line 211 (POST /webmail/?_task=login&_action=login)
```

I spent pointless hours on this, in the end all I had to do was replace my .pw cert for a .rs+.pw one and Roundcube started working, but I still have no idea WHY Roundcube is expecting a certain domain name on the cert.

@alecpl Can you please reopen this and target Roundcube providing something more helpful than 'Unknown error' 
 in the logs when the failure is obviously a mismatching CN?
