### ISSUE TITLE
Uncaught Error: Found unconstructed Spoofchecker

### ISSUE THREAD

**Issue by LwsBtlr** [roundcube/roundcubemail#8537]
getting repeated errors, logged as 
` PHP Fatal error:  Uncaught Error: Found unconstructed Spoofchecker in /usr/local/www/roundcube/program/lib/Roundcube/rcube_spoofchecker.php:54`

when opening mailboxes or messages. Many attempts to fix this, including completely removing and rebuilding RC and all packages required by roundcube to no avail.

Disabled the soiifchecker call and we are back to normal.

```
@@ -1397,7 +1397,7 @@

             // Homograph attack detection (#6891)
             if (!self::$SUSPICIOUS_EMAIL) {
+                // self::$SUSPICIOUS_EMAIL = rcube_spoofchecker::check($mailto);
-                self::$SUSPICIOUS_EMAIL = rcube_spoofchecker::check($mailto);
             }

             if (self::$PRINT_MODE) {
```

Obviously this is temporary, but it’s the only way OI can get RC working.

roundcube-1.5.2,1
Freebsde 13.0

**Comment by alecpl** [comment]
I have no idea what that could be, but sounds more like a PHP bug (maybe BSD related). What PHP version?

**Comment by zlice** [comment]
Found this https://github.com/roundcube/roundcubemail/issues/8537 then this issue

- Void Linux
- php / php-fpm 7.4.30
- nginx 1.20.2

thx lws

**Comment by karolyi** [comment]
I'm also getting this on FreeBSD 13.0

The PHP version is php80-8.0.20.

**Comment by alecpl** [comment]
I'm not sure this error can be catched. Does that work for you with this patch?
```diff
diff --git a/program/lib/Roundcube/rcube_spoofchecker.php b/program/lib/Roundcube/rcube_spoofchecker.php
index 296510c8c..9275df3bd 100644
--- a/program/lib/Roundcube/rcube_spoofchecker.php
+++ b/program/lib/Roundcube/rcube_spoofchecker.php
@@ -47,18 +47,24 @@ class rcube_spoofchecker
         }
 
         // Spoofchecker is part of ext-intl (requires ICU >= 4.2)
-        $checker = new Spoofchecker();
+        try {
+            $checker = new Spoofchecker();
 
-        // Note: The constant (and method?) added in PHP 7.3.0
-        if (defined('Spoofchecker::HIGHLY_RESTRICTIVE')) {
-            $checker->setRestrictionLevel(Spoofchecker::HIGHLY_RESTRICTIVE);
+            // Note: The constant (and method?) added in PHP 7.3.0
+            if (defined('Spoofchecker::HIGHLY_RESTRICTIVE')) {
+                $checker->setRestrictionLevel(Spoofchecker::HIGHLY_RESTRICTIVE);
+            }
+            else {
+                $checker->setChecks(Spoofchecker::SINGLE_SCRIPT | Spoofchecker::INVISIBLE);
+            }
+
+            $result = $checker->isSuspicious($domain);
         }
-        else {
-            $checker->setChecks(Spoofchecker::SINGLE_SCRIPT | Spoofchecker::INVISIBLE);
+        catch (Throwable $e) {
+            rcube::raise_error($e, true);
+            $result = false;
         }
 
-        $result = $checker->isSuspicious($domain);
-
         // TODO: Use areConfusable() to detect ascii-spoofing of some domains, e.g. paypa1.com?
         // TODO: Domains with non-printable characters should be considered spoofed
 
```

**Comment by karolyi** [comment]
I think it can be catched, as the error in the log now changes to:

```
[09-Jul-2022 19:52:30 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type Error as array in /program/lib/Roundcube/rcube.php
:1401
Stack trace:
#0 /program/lib/Roundcube/rcube_spoofchecker.php(64): rcube::raise_error(Object(Error), true)
```

**Comment by alecpl** [comment]
Thanks. Fixed. Note that it just ignores the error, but spoofchecking is still broken. The reason for "Found unconstructed Spoofchecker" looks to me like an internal PHP issue.

**Comment by karolyi** [comment]
Thanks.

Looking forward for the freebsd package release.

**Comment by Sp1l** [comment]
Just ran into this issue in Roundcube 1.6.0 on FreeBSD 13.1 with PHP 8.1.11.

Looks like every other mail requested gets this error:

```
[22-Oct-2022 10:23:31 +0200]: <4cc2e3df> PHP Error: Found unconstructed Spoofchecker in /usr/local/www/roundcube/program/lib/Roundcube/rcube_spoofchecker.php on line 55 (GET /?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=155969&_mbox=INBOX&_framed=1&_action=preview)
```

@karolyi The update was stuck for quite some time, I committed 1.6.0 on 2022-09-18 after maintainer timeout https://github.com/freebsd/freebsd-ports/commit/72ed1c4dd5f42fd755001a099aff0344de45fe7c

**Comment by karolyi** [comment]
Interesting.

I just reinstalled my roundcube jail with php 81.1.11 and roundcube-php81-1.6.0,1 and the errors disappeared; I no longer need to manually to edit the file to make roundcube work.

**Comment by karolyi** [comment]
Hm, this is even more interesting.

I've rebuilt the jail to not use the freebsd package anymore, but rather use the distribution tarball from github. Using that, the error reappeared.

**Comment by vadimkim** [comment]
Hello, @Sp1l and @karolyi 
I have nearly the same components installed recently: roundcube-php81-1.6.0,1 on FreeBSD 13.1 and PHP 8.1.13. Error log contains only this:
```
[28-Dec-2022 10:41:05 +0200]: <23ifb8vs> PHP Error: Found unconstructed Spoofchecker in /usr/local/www/roundcube/program/lib/Roundcube/rcube_spoofchecker.php on line 55 (GET /?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=17642&_mbox=INBOX&_framed=1&_action=preview)
```
Installed from ports. They seems to be updated with your patch. Did you still have this issue? Where to look for the rootcause?

**Comment by karolyi** [comment]
@vadimkim 
I stopped using the freebsd bundled package and created an installscript for myself that simply pulls/updates to the latest release from gihub.

The error message still appears in the roundcube log but since it's catched via that try/catch statement, it no longer leads to a crash.

**Comment by vadimkim** [comment]
Thanks, @karolyi. It seems your solution is better maintainable.

**Comment by rooty0** [comment]
Hey guys, I'd like to share the root cause I've found for people still searching. This is related to the ICU package. As of the moment writing me this message latest FreeBSD port of ICU is "icu-72.1,1". It looks like the version is not compatible with the current php81-intl . Downgrading ICU to "icu-71.1,1" did resolve the issue (don't forget to reinstall php81-intl after downgrading to icu-71.1,1). More details https://forums.freebsd.org/threads/weird-issue-with-php81-intl.87603/
